### PR TITLE
Adds solo-2.0.20

### PR DESCRIPTION
**Pull request by wsilva32**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@mrpollo - Great @wsilva32 done this. Is there any particular testing process needed to confirm this sort of addition?

Any chance we could get an updated Copter/Plane/Rover too? :-)

**Comment by wsilva32** [comment]
I don't know of any existing testing system that checks if the download is valid. I'll try to get to updating Copter/Plane/Rover as well but no promises on timing :)

**Comment by hamishwillee** [comment]
@wsilva32 Thanks! So best to just merge this and test it works?

**Comment by wsilva32** [comment]
You can hold off for just a bit. There's a parameter issue that is preventing the vehicle from taking off that I'm discussing with Tim today.

**Comment by wsilva32** [comment]
Ok, ready for merge when you are!

**Comment by mrpollo** [comment]
lgtm

**Pull request merged**
