### PR TITLE
Add ability to use ArduPilot firmware manifest to download SITL binaries

### PR DESCRIPTION
**Pull request by peterbarker**
With a little bit of work this will also allow `dronekit-sitl` to work on ARM.

I don't have a great solution for parameters yet.

### CODE REVIEW

**Comment by kyrlon** [comment]
when attempting to run `dronekit-sitl copter` this was the error I received:
```
$ dronekit-sitl copter
Traceback (most recent call last):
  File "C:\Users\kyrlon\Documents\Repositories\OUSD\ama - AUTO\py_venv\Scripts\dronekit-sitl-script.py", line 33, in <module>
    sys.exit(load_entry_point('dronekit-sitl==3.3.0', 'console_scripts', 'dronekit-sitl')())
  File "C:\Users\kyrlon\Documents\Repositories\OUSD\ama - AUTO\py_venv\Scripts\dronekit-sitl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\kyrlon\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\kyrlon\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\kyrlon\Documents\Repositories\OUSD\ama - AUTO\py_venv\lib\site-packages\dronekit_sitl\__init__.py", line 240
    os.chmod(target_filepath, 0755)
                                 ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
(py_venv) 
```

I modified line 240 and replaced with `os.chmod(target_filepath, 0o755)` and that seem to do the trick.

This attempt was done in a virtual environment on windows 10
```
$ python --version
Python 3.9.7
(py_venv) 
```

**Comment by nonmeaning** [comment]
i try the new version of "__init__.py" to run dronekit-sitl, but it still doesn't  work. I run it on the nvidia jetson Orin NX. Here are the Tracbacks:
File "/home/heu/miniconda3/envs/UAV-track/bin/dronekit-sitl", line 33, in <module>
    sys.exit(load_entry_point('dronekit-sitl==3.3.0', 'console_scripts', 'dronekit-sitl')())
  File "/home/heu/miniconda3/envs/UAV-track/lib/python3.8/site-packages/dronekit_sitl-3.3.0-py3.8.egg/dronekit_sitl/__init__.py", line 847, in main
    sitl.launch(args, verbose=True)
  File "/home/heu/miniconda3/envs/UAV-track/lib/python3.8/site-packages/dronekit_sitl-3.3.0-py3.8.egg/dronekit_sitl/__init__.py", line 493, in launch
    caps = ArdupilotCapabilities(self.path)
  File "/home/heu/miniconda3/envs/UAV-track/lib/python3.8/site-packages/dronekit_sitl-3.3.0-py3.8.egg/dronekit_sitl/__init__.py", line 402, in __init__
    process = subprocess.Popen([path, '--help'], stdout=subprocess.PIPE)
  File "/home/heu/miniconda3/envs/UAV-track/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/heu/miniconda3/envs/UAV-track/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/heu/.dronekit/sitl/copter-3.3/apm'
 Any help to resolve this queson? Many thanks!

**Comment by i-vis** [comment]
Hi! As @kyrlon mentioned, `0o755` instead of `0755` fixes the code. Also I think there should be a check for `sitl_target` directory, whether it exists or not before `os.makedirs(sitl_target)` ( in def version_list_new_manifest() ), as I had problem with that because that path exists already. After doing these 2 small changes to code in this PR, my dronekit-sitl, MAVproxy, dronekit setup for testing finally works correctly and problems like #153 are gone. Thank you very much, I hope your PR will get updated and merged.

**Comment by peterbarker** [comment]
> Hi! As @kyrlon mentioned, `0o755` instead of `0755` fixes the code. Also I think there should be a check for `sitl_target` directory, whether it exists or not before `os.makedirs(sitl_target)` ( in def version_list_new_manifest() ), as I had problem with that because that path exists already. After doing these 2 small changes to code in this PR, my dronekit-sitl, MAVproxy, dronekit setup for testing finally works correctly and problems like #153 are gone. Thank you very much, I hope your PR will get updated and merged.

Wow.  Some love for a 5-year old PR!

I've made the changes suggested here.  Could people test them, please?  :-)

**Comment by kyrlon** [comment]
> > Hi! As @kyrlon mentioned, `0o755` instead of `0755` fixes the code. Also I think there should be a check for `sitl_target` directory, whether it exists or not before `os.makedirs(sitl_target)` ( in def version_list_new_manifest() ), as I had problem with that because that path exists already. After doing these 2 small changes to code in this PR, my dronekit-sitl, MAVproxy, dronekit setup for testing finally works correctly and problems like #153 are gone. Thank you very much, I hope your PR will get updated and merged.
> 
> Wow. Some love for a 5-year old PR!
> 
> I've made the changes suggested here. Could people test them, please? :-)

AND HE'S BACK!! :)

**Comment by peterbarker** [comment]
@kyrlon many thanks for the testing - I've merged this one now.

I'm going to try to set up an easy release process for this next...

**Pull request merged**
