### PR TITLE
Provide option to preserve eeprom settings across relaunches

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by hamishwillee** [comment]
So you set that value copy_eeprom or whatever =True and you get persistence, otherwise it's a fresh eeprom every time? Or to put it another way, setting copy_eeprom means "use the copied eeprom"? Or does it mean "do a copy of this eeprom and we'll load it next time". It must mean the former, but I feel a bit ambiguous. 

Perhaps a name without ambiguity? use_saved_data - depending on how this actually work?

**Comment by peterbarker** [comment]
On Sun, 15 May 2016, Hamish Willee wrote:

> So you set that value copy_eeprom or whatever =True and you get persistence, otherwise it's a fresh eeprom every time? Or to put it another way, setting copy_eeprom means "use the copied eeprom"? Or does it mean "do a copy of this eeprom and we'll load it next time". It must mean the former, but I feel a bit
> ambiguous.
> 
> Perhaps a name without ambiguity? use_saved_data - depending on how this actually work?

Fair call.  Changed to "use_saved_data=False".

**Comment by hamishwillee** [comment]
I like. I haven't tested this but code looks right. Merging.

**Comment by hamishwillee** [comment]
... and doc in readme/ command line help if not done.

**Pull request merged**
