### PR TITLE
Add ability to point to a local binary

### LINKED ISSUE #13: Would be cool to have a way to point at a local build of flight code.

### PR DESCRIPTION
**Pull request by TShapinsky**
closes #13 
`dronekit-sitl --local ~/src/ardupilot/ArduCopter/ArduCopter.elf`

### CODE REVIEW

**Comment by asetapen** [comment]
@tcr3dr: Can I merge this in? Works for me, and very useful for development!

**Comment by tcr3dr** [comment]
@asetapen That review works for me!

**Comment by hamishwillee** [comment]
Is there any documentation on how this is used? Is it the same as https://github.com/dronekit/dronekit-sitl/issues/13#issuecomment-127346813 ?

**Comment by TShapinsky** [comment]
@hamishlee it is the same

**Comment by hamishwillee** [comment]
Thanks @TShapinsky - much appreciated.

**Pull request merged**
